config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  resources :response_rules
  resources :response_templates
  resources :request_logs, only: [:index, :show]
  match "*_", to: 'customized_response#get', via: [:get, :post]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/request_log.rb
class RequestLog < ApplicationRecord
  belongs_to :response_template, optional: true
end

app/models/response_rule.rb
class ResponseRule < ApplicationRecord
  belongs_to :response_template
end

app/models/response_template.rb
class ResponseTemplate < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include BasicAuth
end

app/controllers/concerns/basic_auth.rb
module BasicAuth
  extend ActiveSupport::Concern

  included do
    before_action :basic_auth
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username_value = ENV.fetch('basic_auth_user', 'foo')
      password_value = ENV.fetch('basic_auth_password', 'bar')

      username == username_value && password == password_value
    end
  end
end

app/controllers/customized_response_controller.rb
class CustomizedResponseController < ApplicationController
  skip_before_action :basic_auth, :verify_authenticity_token

  def get
    error = nil
    response = {}
    begin
      response = CustomizedResponseService.response_for(request)
      raise '500 response requested' if response[:raise_error]
      render response[:payload].dup
    rescue StandardError => e
      error = e
      raise
    ensure
      request.body.rewind
      RequestLog.create!(
        request_path: request.path,
        request_body: request.body.read,
        response_code: response.dig(:payload, :status),
        response_body: response.dig(:payload, :json),
        success: response.dig(:success),
        response_template_id: response.dig(:response_template_id),
        error_text: error ? "#{error.class.name}: #{error.message}" : nil,
      )
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/request_logs_controller.rb
class RequestLogsController < ApplicationController
  def index
    @request_logs = RequestLog.all.preload(:response_template).order(created_at: :desc).limit(1000)
  end

  def show
    @request_log = RequestLog.find(params[:id])
  end
end

app/controllers/response_rules_controller.rb
class ResponseRulesController < ApplicationController
  before_action :set_response_rule, only: [:show, :edit, :update, :destroy]

  # GET /response_rules
  # GET /response_rules.json
  def index
    @response_rules = ResponseRule.all
  end

  # GET /response_rules/1
  # GET /response_rules/1.json
  def show
  end

  # GET /response_rules/new
  def new
    @response_rule = ResponseRule.new
  end

  # GET /response_rules/1/edit
  def edit
  end

  # POST /response_rules
  # POST /response_rules.json
  def create
    @response_rule = ResponseRule.new(response_rule_params)

    respond_to do |format|
      if @response_rule.save
        format.html { redirect_to @response_rule, notice: 'Response rule was successfully created.' }
        format.json { render :show, status: :created, location: @response_rule }
      else
        format.html { render :new }
        format.json { render json: @response_rule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /response_rules/1
  # PATCH/PUT /response_rules/1.json
  def update
    respond_to do |format|
      if @response_rule.update(response_rule_params)
        format.html { redirect_to @response_rule, notice: 'Response rule was successfully updated.' }
        format.json { render :show, status: :ok, location: @response_rule }
      else
        format.html { render :edit }
        format.json { render json: @response_rule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /response_rules/1
  # DELETE /response_rules/1.json
  def destroy
    @response_rule.destroy
    respond_to do |format|
      format.html { redirect_to response_rules_url, notice: 'Response rule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_response_rule
      @response_rule = ResponseRule.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def response_rule_params
      params.require(:response_rule).permit(:name, :path, :response_template_id, :response_code, :conditions, :sleep, :raise_error)
    end
end

app/controllers/response_templates_controller.rb
class ResponseTemplatesController < ApplicationController
  before_action :set_response_template, only: [:show, :edit, :update, :destroy]

  # GET /response_templates
  # GET /response_templates.json
  def index
    @response_templates = ResponseTemplate.all
  end

  # GET /response_templates/1
  # GET /response_templates/1.json
  def show
  end

  # GET /response_templates/new
  def new
    @response_template = ResponseTemplate.new
  end

  # GET /response_templates/1/edit
  def edit
  end

  # POST /response_templates
  # POST /response_templates.json
  def create
    @response_template = ResponseTemplate.new(response_template_params)

    respond_to do |format|
      if @response_template.save
        format.html { redirect_to @response_template, notice: 'Response template was successfully created.' }
        format.json { render :show, status: :created, location: @response_template }
      else
        format.html { render :new }
        format.json { render json: @response_template.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /response_templates/1
  # PATCH/PUT /response_templates/1.json
  def update
    respond_to do |format|
      if @response_template.update(response_template_params)
        format.html { redirect_to @response_template, notice: 'Response template was successfully updated.' }
        format.json { render :show, status: :ok, location: @response_template }
      else
        format.html { render :edit }
        format.json { render json: @response_template.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /response_templates/1
  # DELETE /response_templates/1.json
  def destroy
    @response_template.destroy
    respond_to do |format|
      format.html { redirect_to response_templates_url, notice: 'Response template was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_response_template
      @response_template = ResponseTemplate.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def response_template_params
      params.require(:response_template).permit(:name, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def safe_render_json(content)
    return '<empty>' if content.blank?

    json = JSON.parse(content)
    JSON.pretty_generate(json)
  rescue JSON::ParserError
    content
  end
end

app/helpers/customized_response_helper.rb
module CustomizedResponseHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/response_rules_helper.rb
module ResponseRulesHelper
end

app/helpers/response_templates_helper.rb
module ResponseTemplatesHelper
end

app/views/home/index.html.haml
%h3 
  = link_to 'Response Templates', response_templates_path

%h3 
  = link_to 'Response Rules', response_rules_path

%h3
  = link_to 'Request Log', request_logs_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title MiFakeServer
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield
    %p
      = link_to 'Home', root_path

app/views/request_logs/index.html.haml
%h1 Listing request_logs

%table
  %thead
    %tr
      %th Success
      %th Status
      %th Path
      %th Request(bytes)
      %th Response(bytes)
      %th Template
      %th Created At
      %th Error
      %th

  %tbody
    - @request_logs.each do |request_log|
      %tr
        %td= request_log.success
        %td= request_log.response_code
        %td= request_log.request_path
        %td= request_log.request_body&.size
        %td= request_log.response_body&.size
        %td= link_to request_log.response_template.name, request_log.response_template if request_log.response_template
        %td= request_log.created_at
        %td= request_log.error_text
        %td= link_to 'Show', request_log

app/views/request_logs/show.html.haml
%p#notice= notice

%p
  %b Request path:
  = @request_log.request_path
%p
  %b Request body:
  %pre
    = safe_render_json(@request_log.request_body)
%p
  %b Response code:
  = @request_log.response_code
%p
  %b Response body:
  %pre
    = safe_render_json(@request_log.response_body)
%p
  %b Success:
  = @request_log.success
%p
  %b Response template:
  - if @request_log.response_template
    = link_to @request_log.response_template.name, @request_log.response_template
  - else
    N/A
%p
  %b Error text:
  = @request_log.error_text
%p
  %b Created At:
  = @request_log.created_at

= link_to 'Back', request_logs_path

app/views/response_rules/_form.html.haml
= form_for @response_rule do |f|
  - if @response_rule.errors.any?
    #error_explanation
      %h2= "#{pluralize(@response_rule.errors.count, "error")} prohibited this response_rule from being saved:"
      %ul
        - @response_rule.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :path
    = f.text_field :path
  .field
    = f.label :response_template
    = f.select :response_template_id, ResponseTemplate.order(:name).pluck(:name, :id)
  .field
    = f.label :response_code
    = f.number_field :response_code
  .field
    = f.label :conditions
    = f.text_area :conditions
  .field
    = f.label :sleep
    = f.number_field :sleep
  .field
    = f.label :raise_error
    = f.check_box :raise_error
  .actions
    = f.submit 'Save'

app/views/response_rules/edit.html.haml
%h1 Editing response_rule

= render 'form'

= link_to 'Show', @response_rule
\|
= link_to 'Back', response_rules_path

app/views/response_rules/index.html.haml
%h1 Listing response_rules

%table
  %thead
    %tr
      %th Name
      %th Path
      %th Response template
      %th Response code
      %th Conditions
      %th Sleep
      %th Raise error
      %th
      %th
      %th

  %tbody
    - @response_rules.each do |response_rule|
      %tr
        %td= response_rule.name
        %td= response_rule.path
        %td= link_to response_rule.response_template.name, response_rule.response_template
        %td= response_rule.response_code
        %td= response_rule.conditions
        %td= response_rule.sleep
        %td= response_rule.raise_error
        %td= link_to 'Show', response_rule
        %td= link_to 'Edit', edit_response_rule_path(response_rule)
        %td= link_to 'Destroy', response_rule, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Response rule', new_response_rule_path

app/views/response_rules/new.html.haml
%h1 New response_rule

= render 'form'

= link_to 'Back', response_rules_path

app/views/response_rules/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @response_rule.name
%p
  %b Path:
  = @response_rule.path
%p
  %b Response template:
  = link_to @response_rule.response_template.name, @response_rule.response_template
%p
  %b Response code:
  = @response_rule.response_code
%p
  %b Conditions:
  = @response_rule.conditions
%p
  %b Sleep:
  = @response_rule.sleep
%p
  %b Raise error:
  = @response_rule.raise_error

= link_to 'Edit', edit_response_rule_path(@response_rule)
\|
= link_to 'Back', response_rules_path

app/views/response_templates/_form.html.haml
= form_for @response_template do |f|
  - if @response_template.errors.any?
    #error_explanation
      %h2= "#{pluralize(@response_template.errors.count, "error")} prohibited this response_template from being saved:"
      %ul
        - @response_template.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :body
    = f.text_area :body
  .actions
    = f.submit 'Save'

app/views/response_templates/edit.html.haml
%h1 Editing response_template

= render 'form'

= link_to 'Show', @response_template
\|
= link_to 'Back', response_templates_path

app/views/response_templates/index.html.haml
%h1 Listing response_templates

%table
  %thead
    %tr
      %th Name
      %th Code
      %th
      %th
      %th

  %tbody
    - @response_templates.each do |response_template|
      %tr
        %td= response_template.name
        %td= link_to 'Show', response_template
        %td= link_to 'Edit', edit_response_template_path(response_template)
        %td= link_to 'Destroy', response_template, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Response template', new_response_template_path

app/views/response_templates/new.html.haml
%h1 New response_template

= render 'form'

= link_to 'Back', response_templates_path

app/views/response_templates/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @response_template.name
%p
  %b Body:
  %pre
    = safe_render_json(@response_template.body)

= link_to 'Edit', edit_response_template_path(@response_template)
\|
= link_to 'Back', response_templates_path